document.write("        <div class=\"title\">Menu<\/div>");
document.write("        <ul class=\"mtree transit\">");
document.write("            <li><a href=\"overview\"><i class=\"fa fa-home\"><\/i>Item1<\/a>");
document.write("                <ul>");
document.write("                    <li><a href=\"sub1\">graph1<\/a><\/li>");
document.write("                    <li><a href=\"#\">Sub-menu 2<\/a><\/li>");
document.write("                    <li><a href=\"#\">Sub-menu 3<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/li>");
document.write("            <li><a href=\"#\"><i style=\"font-size:15px\" class=\"fa fa-bar-chart\"><\/i>Item2<\/a>");
document.write("                <ul>");
document.write("                    <li><a href=\"#\">Sub-menu 1<\/a><\/li>");
document.write("                    <li><a href=\"#\">Sub-menu 2<\/a><\/li>");
document.write("                    <li><a href=\"#\">Sub-menu 3<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/li>");
document.write("            <li><a href=\"#\"><i style=\"font-size:16px\" class=\"fa fa-exclamation-triangle\"><\/i>Item3<\/a>");
document.write("                <ul>");
document.write("                    <li><a href=\"#\">Sub-menu 1<\/a><\/li>");
document.write("                    <li><a href=\"#\">Sub-menu 2<\/a><\/li>");
document.write("                    <li><a href=\"#\">Sub-menu 3<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/li>");
document.write("        <\/ul>");