document.write("        <div class=\"title\">News<\/div>");
document.write("        <div class=\"news-box\">");
document.write("            <div class=\"news-thumb\"><\/div>");
document.write("            <div class=\"news-text\">");
document.write("            Lorem ipsum dolor sit amet, vix discere electram adipiscing no, delectus phaedrum eam id. ");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"news-box\">");
document.write("            <div class=\"news-thumb\"><\/div>");
document.write("            <div class=\"news-text\">");
document.write("            Lorem ipsum dolor sit amet, vix discere electram adipiscing no, delectus phaedrum eam id  ");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"news-box\">");
document.write("            <div class=\"news-thumb\"><\/div>");
document.write("            <div class=\"news-text\">");
document.write("            Lorem ipsum dolor sit amet, vix discere electram adipiscing no, delectus phaedrum eam id.");
document.write("            <\/div>");
document.write("        <\/div>");